CREATE TABLE users (
  id MEDIUMINT UNSIGNED AUTO_INCREMENT,
  loginId VARCHAR(50) UNIQUE COMMENT'LOGIN_ID_COLUMN',
  password BLOB COMMENT'PASSWORD_COLUMN',
  PRIMARY KEY (id)
) ENGINE = InnoDB AUTO_INCREMENT = 1 ROW_FORMAT = DEFAULT CHARACTER SET utf8;
