CREATE TABLE users (
  id MEDIUMINT UNSIGNED AUTO_INCREMENT COMMENT'회원 인덱스',
  loginId VARCHAR(50) UNIQUE COMMENT'회원 ID - EMAIL',
  passwd BLOB COMMENT'회원 암호',
  PRIMARY KEY (id)
) ENGINE = InnoDB AUTO_INCREMENT = 1 ROW_FORMAT = DEFAULT CHARACTER SET utf8;
